FROM python:3.10

WORKDIR /temp

COPY ./requirements.txt /temp/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /temp/requirements.txt

COPY ./app /temp/app

CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "3000"]